spring.datasource.url=jdbc:mysql://localhost:3306/simardb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=DatabaseProject7

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.application.name=simaar

jwt.secret=simarSuperSecretKey2024PleaseChangeThisToSomethingLonger
jwt.expiration=86400000